// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Storage.Infrastructure.Persistence.SqlServer;

#nullable disable

namespace Storage.Infrastructure.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    partial class StorageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Storage.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Metadata");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FileId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ip")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("OccurredAt");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Actor");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("AuditLogId");

                    b.HasIndex("FileId");

                    b.HasIndex("FileId1");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("Storage.Domain.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Checksum")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("OriginalName");

                    b.Property<string>("OwnerService")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("PreviewFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ThumbnailFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("PreviewFileId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ThumbnailFileId");

                    b.HasIndex("TenantId", "CategoryId");

                    b.HasIndex("TenantId", "OwnerService");

                    b.ToTable("Files", null, t =>
                        {
                            t.HasCheckConstraint("CK_Files_Status", "Status IN ('pending','scanning','ready','quarantined','deleted')");
                        });
                });

            modelBuilder.Entity("Storage.Domain.Entities.FileCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AiValidationStrategy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AllowedExtensions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllowedMimeTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllowedOwnerServices")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AntivirusRequired")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsLargeFile")
                        .HasColumnType("bit");

                    b.Property<string>("LifecycleTier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("MaxSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("MultipartThresholdBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("PreviewStrategy")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("RequiresAiValidation")
                        .HasColumnType("bit");

                    b.Property<int?>("RetentionDays")
                        .HasColumnType("int");

                    b.Property<bool>("SupportsPreview")
                        .HasColumnType("bit");

                    b.Property<string>("ThumbnailSizes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("FileCategories");
                });

            modelBuilder.Entity("Storage.Domain.Entities.FilePermission", b =>
                {
                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrincipalType")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PrincipalId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Permission")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid?>("FileId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FileId", "PrincipalType", "PrincipalId", "Permission");

                    b.HasIndex("FileId1");

                    b.ToTable("FilePermissions", null, t =>
                        {
                            t.HasCheckConstraint("CK_FilePermissions_PrincipalType", "PrincipalType IN ('service','user')");
                        });
                });

            modelBuilder.Entity("Storage.Domain.Entities.FileTag", b =>
                {
                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("FileId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("FileId", "Key");

                    b.HasIndex("FileId1");

                    b.ToTable("FileTags");
                });

            modelBuilder.Entity("Storage.Domain.Entities.FileVersion", b =>
                {
                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FileId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("FileId", "VersionNumber");

                    b.HasIndex("FileId1");

                    b.ToTable("FileVersions");
                });

            modelBuilder.Entity("Storage.Domain.Entities.AuditEntry", b =>
                {
                    b.HasOne("Storage.Domain.Entities.File", null)
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Storage.Domain.Entities.File", null)
                        .WithMany("AuditEntries")
                        .HasForeignKey("FileId1");
                });

            modelBuilder.Entity("Storage.Domain.Entities.File", b =>
                {
                    b.HasOne("Storage.Domain.Entities.File", null)
                        .WithMany()
                        .HasForeignKey("PreviewFileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Storage.Domain.Entities.File", null)
                        .WithMany()
                        .HasForeignKey("ThumbnailFileId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Storage.Domain.Entities.FilePermission", b =>
                {
                    b.HasOne("Storage.Domain.Entities.File", null)
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Storage.Domain.Entities.File", null)
                        .WithMany("Permissions")
                        .HasForeignKey("FileId1");
                });

            modelBuilder.Entity("Storage.Domain.Entities.FileTag", b =>
                {
                    b.HasOne("Storage.Domain.Entities.File", null)
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Storage.Domain.Entities.File", null)
                        .WithMany("Tags")
                        .HasForeignKey("FileId1");
                });

            modelBuilder.Entity("Storage.Domain.Entities.FileVersion", b =>
                {
                    b.HasOne("Storage.Domain.Entities.File", null)
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Storage.Domain.Entities.File", null)
                        .WithMany("Versions")
                        .HasForeignKey("FileId1");
                });

            modelBuilder.Entity("Storage.Domain.Entities.File", b =>
                {
                    b.Navigation("AuditEntries");

                    b.Navigation("Permissions");

                    b.Navigation("Tags");

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
